### ISSUE TITLE
Server based error occured

### ISSUE THREAD

**Issue by bernandez** [smswithoutborders/SMSWithoutBorders-Gateway-Client#18]
When trying to check the status of the API, I recieve a server based error occurred.
below is what I receive on my terminal.
127.0.0.1 - - [15/Feb/2022 16:59:51] "GET /system/state HTTP/1.1" 500 -

**Comment by sherlockwisdom** [comment]
Please which branch are you working with?

**Comment by bernandez** [comment]
I am working with the Deku API.

**Comment by sherlockwisdom** [comment]
Thank you, but please which branch on this project are you working with? 
`master` or `alpha` or `alpha_stable`

**Comment by bernandez** [comment]
Please how can i detect the branch am working with. Cause I just cloned the repo and launched the API

**Comment by bernandez** [comment]
I just checked and looks like i am working on the alpha branch

**Comment by bernandez** [comment]
Do i need to get the Deku router running before the API functions properly?
