### ISSUE TITLE
Unable to get gateway client state from api

### ISSUE THREAD

**Issue by nSedrickm** [smswithoutborders/SMSWithoutBorders-Gateway-Client#51]
GET /system/state endpoint missing

**Comment by sherlockwisdom** [comment]
now available: https://github.com/smswithoutborders/SMSWithoutBorders-Gateway-Client/commit/99217ed1169e2bb62fe1621602096864fb741dff

**Comment by nSedrickm** [comment]
Thanks!

**Comment by nSedrickm** [comment]
@sherlockwisdom thought its worth mentioning here that the states only work correctly if inbound and outbound are running as system services. I was initially running the python scripts directly passing `--module` but it didn't work

**Comment by sherlockwisdom** [comment]
That's correct, states are only services. We can add another endpoint to test if API is running.
